"""C64 ZERO_PAGE Registers"""
from .common import Register, Register16, Component

class _ZP(Component):
    # Flag: Subscript Reference to an Array or User-Defined Function Call (FN) This flag is used by the PT...
    subflg = Register(16)

    # Flag: Is Data Input to GET, READ or INPUT? Since the keywords GET, INPUT, and READ perform similar f...
    inpflg = Register(17)

    # Flag: Sign of the Result of the TAN or SIN Function This location is used to determine whether the s...
    tansgn = Register(18)

    # Current I/O Channel (CMD Logical File) Number Whenever BASIC inputs or outputs data, it looks here t...
    channl = Register(19)

    # -$ 15 LINNUM Integer Line Number Value The target line number for GOTO, LIST, ON, and GOSUB is store...
    reg_20 = Register16(20)

    # Pointer to the Next Available Space in the Temporary String Stack This location points to the next a...
    temppt = Register(22)

    # -$ 18 LASTPT Pointer to the Address of the Last String in the Temporary String Stack This pointer in...
    reg_23 = Register16(23)

    # rll...
    reg_24 = Register16(24)

    # Descriptor Stack for Temporary Strings The temporary string descriptor stack contains information ab...
    tempst = Register(25)

    # rl2...
    reg_26 = Register16(26)

    # rl3...
    reg_28 = Register16(28)

    # rl4...
    reg_30 = Register16(30)

    # rl5...
    reg_32 = Register16(32)

    # Miscellaneous Temporary Pointers and Save Area r~) This area is used by many BASIC routines to hold ...
    index = Register(34)

    # string Used for string input...
    reg_36 = Register16(36)

    # I { Floating Point Multiplication Work Area This location is used by BASIC multiplication and divisi...
    sesho = Register(38)

    # cunentSetWidth The width of each character card in the current character set in pixels...
    reg_39 = Register16(39)

    # cunentHelght The height of each character card in the current character set in pixels...
    reg_41 = Register(41)

    # currentlndexTable Size of each character card in bytes...
    reg_42 = Register16(42)

    # I — j Pointer to the Start of BASIC Program Text This two-byte pointer lets BASIC know where program...
    txttab = Register16(43)

    # cardDotaPolnter A pointer to the location where the actual graphics data for the character is stored...
    reg_44 = Register16(44)

    # Pointer to the Start of the BASIC Variable Storage Area This location points to the address which ma...
    vartab = Register16(45)

    # cunentMode This location is used to store a flag indicating the current characterdrawing mode. Bit 7...
    reg_46 = Register(46)

    # Pointer to the Start of the BASIC Array Storage Area This location points to the address of the end ...
    arytab = Register16(47)

    # mouseOn This location is used for flags that indicate whether the mouse pointer, menus, and/or icons...
    reg_48 = Register(48)

    # Pointer to End of the BASIC Array Storage Area (+1), and the Start of Free RAM This location points ...
    strend = Register16(49)

    # Pointer to the Bottom of the String Text Storage Area This pointer marks the current end of the stri...
    fretop = Register16(51)

    # wlndowBottom The bottom line of the window for purposes of text clipping...
    reg_52 = Register(52)

    # Temporary Pointer for Strings This is used as a temporary pointer to the most current string added b...
    frespc = Register16(53)

    # Pointer to the Highest Address Used by BASIC The power-on/reset routine tests each byte of RAM until...
    memsiz = Register16(55)

    # Current BASIC Line Number This location contains the line number of the BASIC statement which is cur...
    curlin = Register16(57)

    # mouseXPositlon The current horizontal screen position (0-319) of the mouse pointer...
    reg_58 = Register16(58)

    # Previous BASIC Line Number When program execution ends, the last line number executed is stored here...
    oldlin = Register16(59)

    # mouseYPosition The current vertical position (0-199) of the mouse pointer...
    reg_60 = Register(60)

    # Pointer to the Address of the Current BASIC Statement This location contains the address (not the li...
    oldtxt = Register16(61)

    # Current DATA Line Number This location holds the line number of the current DATA statement being REA...
    datlin = Register16(63)

    # Pointer to the Address of the Current DATA Item This location points to the address (not the line nu...
    datptr = Register16(65)

    # Pointer to the Source of GET, READ, or INPUT Information READ, INPUT, and GET all use this as a poin...
    inpptr = Register16(67)

    # Current BASIC Variable Name The current variable name being searched for is stored here, in the same...
    varnam = Register16(69)

    # Pointer to the Current BASIC Variable Value This location points to the address of the descriptor of...
    varpnt = Register16(71)

    # Temporary Pointer to the Index Variable Used by FOR The address of the BASIC variable which is the s...
    forpnt = Register16(73)

    # Math Operator Table Displacement This location is used during the evaluation of mathematical express...
    opptr = Register16(75)

    # Mask for Comparison Operation The expression evaluation routine creates a mask here which lets it kn...
    opmask = Register(77)

    # Pointer to the Current FN Descriptor During function definition (DEF FN) this location is used as a ...
    defpnt = Register16(78)

    # Temporary Pointer to the Current String Descriptor The string assignment and handling routines use t...
    dscpnt = Register(80)

    # Constant for Garbage Collection The constant contained here lets the garbage collection routines kno...
    f0ur6 = Register(83)

    # Jump to Function Instruction The first byte is the 6502 JMP instruction ($4C), followed by the addre...
    jmper = Register(84)

    # Numeric Work Area This is a very busy work area, used by many routines....
    basic = Register(87)

    # Floating Point Accumulator #1: Exponent This exponent represents the closest power of two to the num...
    facexp = Register(97)

    # Floating Point Accumulator #1: Mantissa The most significant digit can be assumed to be a 1 (remembe...
    facho = Register(98)

    # Floating Point Accumulator #1: Sign A value of 0 here indicates a positive number, while a value of ...
    facsgn = Register(102)

    # Number of Terms in a Series Evaluation This location is used by mathematical formula evaluation rout...
    sgnflg = Register(103)

    # ' I Floating Point Accumulator #1: Overflow Digit This location contains the overflow byte. The over...
    bits = Register(104)

    # Floating Point Accumulator #2: Exponent...
    argexp = Register(105)

    # Floating Point Accumulator #2: Mantissa...
    argho = Register(106)

    # Floating Point Accumulator #2: Sign...
    argsgn = Register(110)

    # Result of a Sign Comparison of Accumulator #1 to Accumulator #2 Used to indicate whether the two Flo...
    arisgn = Register(111)

    # Low Order Mantissa Byte of Floating Point Accumulator #1 (For Rounding) If the mantissa of the float...
    facov = Register(112)

    # Series Evaluation Pointer This location points to the address of a temporary table of values built i...
    fbufpt = Register16(113)

    # INC TXTPTR ,...
    chrget = Register(115)

    # CHRGOT ,...
    bne = Register(117)

    # TXTPTR +1 ;...
    inc = Register(119)

    # LDA ;...
    chrgot = Register(121)

    # $0207 ; n...
    txtptr = Register(122)

    # CMP #$3A ;...
    pointb = Register(124)

    # EXIT...
    bcs = Register(126)

    # = STOP key pressed VIC owners will notice that the 64's keyboard matrix is very different from the V...
    reg_127 = Register(127)

    # ...
    end = Register(128)

    # ...
    for = Register(129)

    # ...
    next = Register(130)

    # ...
    data = Register(131)

    # *...
    input = Register(132)

    # ...
    dim = Register(134)

    # ...
    read = Register(135)

    # ...
    let = Register(136)

    # ...
    goto = Register(137)

    # ...
    run = Register(138)

    # ...
    if = Register(139)

    # ...
    restore = Register(140)

    # ...
    gosub = Register(141)

    # ...
    return = Register(142)

    # ...
    rem = Register(143)

    # ...
    stop = Register(144)

    # ...
    on = Register(145)

    # ...
    wait = Register(146)

    # ...
    load = Register(147)

    # ...
    save = Register(148)

    # ...
    verify = Register(149)

    # ...
    def = Register(150)

    # ...
    poke = Register(151)

    # *...
    print = Register(152)

    # ...
    cont = Register(154)

    # ...
    list = Register(155)

    # ...
    clr = Register(156)

    # ...
    cmd = Register(157)

    # ...
    sys = Register(158)

    # ...
    open = Register(159)

    # ...
    close = Register(160)

    # ...
    get = Register(161)

    # ...
    new = Register(162)

    # (...
    tab = Register(163)

    # ...
    to = Register(164)

    # ...
    fn = Register(165)

    # (...
    spc = Register(166)

    # ...
    then = Register(167)

    # ...
    not = Register(168)

    # 3. The math operators found in OPTAB at 41088 ($A080), in the token number order indicated (token nu...
    step = Register(169)

    # RS-232 Input Byte Buffer/Cassette Temporary Storage Serial routines use this area to reassemble the ...
    sidata = Register(170)

    # RS-232 Input Parity/Cassette Leader Counter This location is used to help detect if data was lost du...
    riprty = Register(171)

    # Pointer to the Starting Address of a Load/Screen Scrolling The pointer to the start of the RAM area ...
    sal = Register16(172)

    # ...
    reg_173 = Register(173)

    # Pointer to Ending Address of Load (End of Program) This location is set by the Kemal routine SAVE to...
    eal = Register16(174)

    # ...
    reg_175 = Register(175)

    # Tape Timing Location 176 ($B0) is used to determine the value of the adjustable timing constant at 1...
    cmpo = Register16(176)

    # ...
    reg_177 = Register(177)

    # l Pointer: Start of Tape Buffer On power-on, this pointer is set to the address of the cassette buff...
    tape = Register16(178)

    # Operator / (DIVIDE) t (EXPONENTIATE) AND (LOGICAL AND) OR (LOGICAL OR) > (GREATER THAN) = (EQUAL TO)...
    reg_179 = Register(179)

    # ...
    sgn = Register(180)

    # ...
    int = Register(181)

    # ...
    abs = Register(182)

    # ...
    usr = Register(183)

    # ...
    fre = Register(184)

    # ...
    pos = Register(185)

    # ...
    sqr = Register(186)

    # ...
    rnd = Register(187)

    # ...
    log = Register(188)

    # ...
    exp = Register(189)

    # ...
    cos = Register(190)

    # 57963 SE26B...
    sin = Register(191)

    # 58036 SE2B4...
    tan = Register(192)

    # 58126 SE30E...
    atn = Register(193)

    # 47117 SB80D...
    peek = Register(194)

    # 46972 SB77C...
    lbn = Register(195)

    # $ 46181 SB465...
    str = Register(196)

    # ...
    val = Register(197)

    # ...
    asc = Register(198)

    # $ 46828 SB6EC...
    chr = Register(199)

    # 46848 SB700...
    lefts = Register(200)

    # 46892 SB72C...
    rights = Register(201)

    # ...
    mids = Register(202)

    # Matrix Coordinate of Current Key Pressed The keyscan interrupt routine uses this location to indicat...
    sfdx = Register(203)

    # Cursor Blink Enable: 0= Flash Cursor When this flag is set to a nonzero value, it indicates to the r...
    blnsw = Register(204)

    # Timer: Countdown to Blink Cursor The interrupt routine that blinks the cursor uses this location to ...
    blnct = Register(205)

    # Character under Cursor The cursor is formed by printing the inverse of the character that occupies t...
    gdbln = Register(206)

    # Flag: Was Last Cursor Blink on or off? This location keeps track of whether, during the current curs...
    blnon = Register(207)

    # Flag: Input from Keyboard or Screen This flag is used by the Kemal CHRIN (61783, $F157) routine to i...
    crsw = Register(208)

    # Pointer to the Address of the Current Screen Line This location points to the address in screen RAM ...
    pnt = Register16(209)

    # Cursor Column on Current Line The number contained here is the cursor column position within the log...
    pntr = Register(211)

    # CkTSW Flag: Editor in Quote Mode? 0=No A nonzero value in this location indicates that the editor is...
    reg_212 = Register(212)

    # Maximum Length of Physical Screen Line The line editor uses this location when the end of a line has...
    lnmx = Register(213)

    # Current Cursor Physical Line Number This location contains the current physical screen line position...
    tblx = Register(214)

    # U Temporary Storage Area for ASCII Value of Last Character Printed ^ The ASCII value of the last cha...
    reg_215 = Register(215)

    # Flag: Insert Mode (Any Number Greater Than 0 Is the Number of Inserts) When the INST key is pressed,...
    insrt = Register(216)

    # l Screen Line Link Table/Editor Temporary Storage This table contains 25 entries, one for each row o...
    ldtb = Register(217)

    # = Commodore logo key pressed...
    reg_223 = Register(223)

    # = space bar pressed ^...
    reg_239 = Register(239)

    # Pointer to the Address of the Current Screen Color RAM Location This pointer is synchronized with th...
    user = Register16(243)

    # Vector: Keyboard Decode Table KEYTAB points to the address of the keyboard matrix lookup table curre...
    keytab = Register16(245)

    # Pointer: RS-232 Input Buffer When device number 2 (the RS-232 channel) is opened, two buffers of 256...
    ribuf = Register16(247)

    # Pointer: RS-232 Output Buffer ^ , This location points to the address of the 256-byte output buffer ...
    robuf = Register16(249)

    # = CTRL key pressed 27...
    reg_251 = Register(251)

    # = «- key pressed...
    reg_253 = Register(253)

    # = 1 key pressed...
    reg_254 = Register(254)

    # BASIC Temporary Data for Floating Point to ASCII Conversion This location is used for temporary stor...
    baszpt = Register(255)

ZP = _ZP()
